name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Chạy khi có push lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.1" # Chỉnh sửa version Flutter nếu cần

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --base-href "/portfolio_thanh_tung/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: portfolio-page
          folder: build/web

      - name: Add redirect for Flutter Web
        run: |
          echo '<script>location.replace("/your-repository"+location.pathname+location.search)</script>' > build/web/404.html

